import { useLocation, useNavigate } from "react-router-dom";
import { generateReport } from "../utils/generateReport";
import {
  FileText,
  Download,
  ShieldAlert,
  ShieldCheck,
  Clock,
  Layers,
  Server,
  ArrowLeft,
  CheckCircle2,
  Printer
} from "lucide-react";

export default function ReportPage() {
  const { state } = useLocation();
  const navigate = useNavigate();

  const report = state?.report;

  if (!report) {
    return (
      <div className="min-h-[70vh] flex flex-col items-center justify-center">
        <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm max-w-md text-center">
          <div className="h-12 w-12 rounded-2xl bg-slate-100 text-slate-500 flex items-center justify-center mx-auto mb-3">
            <FileText size={24} />
          </div>
          <h2 className="text-base font-bold text-slate-900">No Incident Dossier Active</h2>
          <p className="text-xs text-slate-500 mt-1 leading-relaxed">
            To generate and inspect a formal incident dossier, navigate to any forensic log artifact and launch the VIRA AI investigation.
          </p>
          <button
            onClick={() => navigate("/")}
            className="mt-4 inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold transition cursor-pointer"
          >
            <span>Return to Command Surface</span>
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* DOSSIER HEADER */}
      <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
          <div className="flex items-center gap-3">
            <button
              onClick={() => navigate(-1)}
              className="p-2 rounded-xl border border-slate-200 hover:bg-slate-50 text-slate-500 hover:text-slate-900 transition cursor-pointer"
              title="Return"
            >
              <ArrowLeft size={18} />
            </button>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-xl font-bold tracking-tight text-slate-900">
                  SOC Security Incident Dossier
                </h1>
                <span className="text-[10px] font-mono font-bold uppercase px-2 py-0.5 rounded bg-emerald-100 text-emerald-800 border border-emerald-200">
                  CLASSIFIED SOC LEVEL-2
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-0.5">
                Autogenerated forensic findings synthesized by VIRA Autonomous AI Engine
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => generateReport(report)}
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold shadow-md shadow-blue-500/20 transition cursor-pointer"
            >
              <Download size={15} />
              <span>Download PDF Incident Dossier</span>
            </button>
          </div>
        </div>

        {/* METADATA STRIP */}
        <div className="mt-4 grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
          <div className="p-3 bg-slate-50 rounded-xl border border-slate-200/60">
            <span className="text-[10px] uppercase font-bold text-slate-400">Target Artifact</span>
            <p className="font-mono font-bold text-slate-900 mt-0.5 truncate">{report.file}</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-xl border border-slate-200/60">
            <span className="text-[10px] uppercase font-bold text-slate-400">Date Generated</span>
            <p className="font-mono font-bold text-slate-900 mt-0.5">{new Date().toLocaleDateString()}</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-xl border border-slate-200/60">
            <span className="text-[10px] uppercase font-bold text-slate-400">MITRE Techniques</span>
            <p className="font-mono font-bold text-blue-600 mt-0.5">{report.mitre?.length || 0} Mapped</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-xl border border-slate-200/60">
            <span className="text-[10px] uppercase font-bold text-slate-400">Isolated IOCs</span>
            <p className="font-mono font-bold text-rose-600 mt-0.5">{report.iocs?.length || 0} Indicators</p>
          </div>
        </div>
      </div>

      {/* EXECUTIVE SUMMARY */}
      <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs">
        <div className="flex items-center gap-2 pb-3 border-b border-slate-100">
          <ShieldCheck size={18} className="text-blue-600" />
          <h2 className="text-sm font-bold text-slate-900">
            Executive AI Assessment & Root Cause Analysis
          </h2>
        </div>
        <p className="mt-4 text-xs leading-relaxed text-slate-800 whitespace-pre-wrap bg-slate-50 p-4 rounded-xl border border-slate-200/80 font-sans">
          {report.summary}
        </p>
      </div>

      {/* MITRE ATT&CK MAPPINGS */}
      {report.mitre && report.mitre.length > 0 && (
        <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs">
          <div className="flex items-center gap-2 pb-3 border-b border-slate-100">
            <Layers size={18} className="text-indigo-600" />
            <h2 className="text-sm font-bold text-slate-900">
              Correlated MITRE ATT&CK Techniques
            </h2>
          </div>
          <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-3">
            {report.mitre.map((m, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl border border-slate-200 bg-slate-50/60"
              >
                <div className="flex items-center justify-between">
                  <span className="font-mono text-xs font-bold text-blue-600 bg-blue-50 px-2 py-0.5 rounded border border-blue-200">
                    {m.id}
                  </span>
                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">
                    {m.tactic}
                  </span>
                </div>
                <p className="text-xs font-bold text-slate-900 mt-2">{m.name}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ISOLATED INDICATORS OF COMPROMISE */}
      {report.iocs && report.iocs.length > 0 && (
        <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs">
          <div className="flex items-center gap-2 pb-3 border-b border-slate-100">
            <Server size={18} className="text-rose-600" />
            <h2 className="text-sm font-bold text-slate-900">
              Isolated Indicators of Compromise (IOCs)
            </h2>
          </div>
          <div className="mt-4 flex flex-wrap gap-2">
            {report.iocs.map((ioc, idx) => (
              <span
                key={idx}
                className="px-3 py-1 bg-slate-100 text-slate-800 text-xs font-mono rounded-lg border border-slate-200"
              >
                {ioc}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* CHRONOLOGICAL KILL CHAIN TIMELINE */}
      {report.timeline && report.timeline.length > 0 && (
        <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-xs">
          <div className="flex items-center gap-2 pb-3 border-b border-slate-100">
            <Clock size={18} className="text-blue-600" />
            <h2 className="text-sm font-bold text-slate-900">
              Chronological Kill Chain Sequence
            </h2>
          </div>
          <div className="mt-4 space-y-3">
            {report.timeline.map((item, idx) => (
              <div
                key={idx}
                className="p-3 rounded-xl bg-slate-50 border border-slate-200/70 flex items-center justify-between text-xs"
              >
                <div>
                  <span className="font-mono text-blue-600 font-bold">{item.time}</span>
                  <p className="font-bold text-slate-900 mt-0.5">{item.event}</p>
                </div>
                {item.ip && (
                  <span className="font-mono text-[11px] bg-slate-200/70 px-2 py-0.5 rounded text-slate-700">
                    {item.ip}
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}