import { useLocation } from "react-router-dom";
import { generateReport } from "../utils/generateReport";

export default function ReportPage() {
  const { state } = useLocation();

const report = state?.report;
if (!report) {
  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-950 text-white">
      <h1 className="text-2xl">
        No report available.
      </h1>
    </div>
  );
}

  return (
    <div className="min-h-screen bg-slate-950 p-8 text-white">

      <h1 className="text-4xl font-bold text-cyan-400">
        Incident Report
      </h1>

      <p className="mt-2 text-slate-400">
        Generated by VIRA
      </p>

      <div className="mt-8 rounded-xl bg-slate-900 p-6">

        <h2 className="text-2xl font-semibold">
          Uploaded File
        </h2>

        <p className="mt-3 text-slate-300">
          {report.file}
        </p>

      </div>

      <div className="mt-6 rounded-xl bg-slate-900 p-6">

        <h2 className="text-2xl font-semibold">
          AI Investigation Summary
        </h2>

        <p className="mt-3 whitespace-pre-wrap text-slate-300">
          {report.summary}
        </p>

      </div>

      <div className="mt-6 rounded-xl bg-slate-900 p-6">

        <h2 className="text-2xl font-semibold">
          MITRE ATT&CK
        </h2>

        <div className="mt-4 space-y-3">

          {report.mitre.map((item, index) => (

            <div
              key={index}
              className="rounded-lg bg-slate-800 p-4"
            >
              <p className="font-bold text-cyan-400">
                {item.id}
              </p>

              <p>{item.name}</p>

            </div>

          ))}

        </div>

      </div>

      <div className="mt-6 rounded-xl bg-slate-900 p-6">

        <h2 className="text-2xl font-semibold">
          Indicators of Compromise
        </h2>

        <ul className="mt-4 list-disc pl-6">

          {report.iocs.map((ioc, index) => (
            <li key={index}>{ioc}</li>
          ))}

        </ul>

      </div>

      <div className="mt-6 rounded-xl bg-slate-900 p-6">

        <h2 className="text-2xl font-semibold">
          Investigation Timeline
        </h2>

        <div className="mt-4 space-y-4">
  {report.timeline.map((item, index) => (
    <div
      key={index}
      className="rounded-lg bg-slate-800 p-4"
    >
      <p className="font-semibold text-cyan-400">
        {item.time}
      </p>

      <p className="mt-2 text-white">
        {item.event}
      </p>

      <p className="mt-1 text-slate-400">
        Source IP: {item.ip}
      </p>
    </div>
  ))}
</div>

      </div>

      <div className="mt-8 flex justify-center">

       <button
  onClick={() => generateReport(report)}
  className="rounded-xl bg-cyan-600 px-10 py-4 text-lg font-semibold hover:bg-cyan-500"
>
  Download PDF Report
</button>

      </div>

    </div>
  );
}